In [8]:
import numpy as np

In [16]:
my_array = np.array([2, 3, 4])
print(my_array)

[2 3 4]


In [19]:
print(type(my_array))
print(type(my_array[0]))
print(my_array.dtype)

num = int(my_array[0])
print(type(num))

<class 'numpy.ndarray'>
<class 'numpy.int32'>
int32
<class 'int'>


In [29]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(my_array)
print(my_array.size)
print(my_array.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)


In [47]:
a1 = np.reshape(my_array, (1, 12))
print(a1)
a1 = np.reshape(my_array, (12,))
print(a1)
print(a1.size)
print(a1.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
12
(12,)


In [48]:
print(my_array)
a1 = np.reshape(my_array, (2, -1), order='C')
print(a1)
print(a1.size)
print(a1.shape)
a1 = np.reshape(my_array, (2, 6), order='F')
print(a1)
print(a1.size)
print(a1.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
12
(2, 6)
[[ 1  9  6  3 11  8]
 [ 5  2 10  7  4 12]]
12
(2, 6)


In [44]:
print(my_array)
a2 = my_array.flatten()
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [57]:
print(np.zeros((3, 5), dtype=np.int32))
print(np.ones((3, 5), dtype=np.int32))
print(np.full((3, 5), 5, dtype=np.int32))
print(np.empty((3, 5)))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [59]:
import math
print(np.arange(0, 2, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]


In [61]:
print(np.linspace(0, 2, 21))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2. ]


In [66]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])

print(a1)
print(a2)
print(np.hstack((a1, a2)))
print(np.vstack((a1, a2)))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [70]:
print(a1)
print(a1[0:, 1])

[[1 2 3]
 [4 5 6]]
[2 5]


In [71]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [72]:
i = np.array([[0, 1], [1, 2]])
j = np.array([[2, 1], [3, 3]])

In [74]:
print(a[i, j])

[[ 2  5]
 [ 7 11]]


In [82]:
a = np.arange(12).reshape(3, 4)
print(a)
b = a > 4
print(b)
a[b] = 0
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


In [85]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])
print(a1)
print(a2)
print(a1 + a2)
print(a1 * 3)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[[ 3  6  9]
 [12 15 18]]


In [90]:
a1 = np.array([[1, 8, 2], [7, 3, 6]])
print(a1)
print(np.min(a1, axis=1))

[[1 8 2]
 [7 3 6]]
[1 3]


In [91]:
a = np.arange(12).reshape(3, 4)
b = a
b[0, 0] = 100
print(b)
print(a)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [92]:
a = np.arange(12).reshape(3, 4)
b = a.view()
b[0, 0] = 100
print(b)
print(a)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [93]:
a = np.arange(12).reshape(3, 4)
b = a.copy()
b[0, 0] = 100
print(b)
print(a)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [94]:
import pandas as pd

In [95]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [96]:
dates = pd.date_range("20230101", periods=6)
print(dates)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')


In [98]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=["C1", "C2", "C3", "C4"])
print(df)

                  C1        C2        C3        C4
2023-01-01 -0.436596  0.407192  0.088817  0.347263
2023-01-02  0.633264  1.186989  0.934845  1.244085
2023-01-03  0.905392  0.176422  0.945018 -0.821895
2023-01-04  0.119293  0.083757 -1.178566  0.043998
2023-01-05 -1.926825  0.552893  1.103002  2.670238
2023-01-06  0.108019  1.055340 -0.786042 -1.564110


In [100]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


In [101]:
print(df)

                  C1        C2        C3        C4
2023-01-01 -0.436596  0.407192  0.088817  0.347263
2023-01-02  0.633264  1.186989  0.934845  1.244085
2023-01-03  0.905392  0.176422  0.945018 -0.821895
2023-01-04  0.119293  0.083757 -1.178566  0.043998
2023-01-05 -1.926825  0.552893  1.103002  2.670238
2023-01-06  0.108019  1.055340 -0.786042 -1.564110


In [103]:
print(df["C1"])
print(df.C1)

2023-01-01   -0.436596
2023-01-02    0.633264
2023-01-03    0.905392
2023-01-04    0.119293
2023-01-05   -1.926825
2023-01-06    0.108019
Freq: D, Name: C1, dtype: float64
2023-01-01   -0.436596
2023-01-02    0.633264
2023-01-03    0.905392
2023-01-04    0.119293
2023-01-05   -1.926825
2023-01-06    0.108019
Freq: D, Name: C1, dtype: float64


In [104]:
print(df[0:3])

                  C1        C2        C3        C4
2023-01-01 -0.436596  0.407192  0.088817  0.347263
2023-01-02  0.633264  1.186989  0.934845  1.244085
2023-01-03  0.905392  0.176422  0.945018 -0.821895


In [106]:
print(df["2023-01-01":"2023-01-04"])

                  C1        C2        C3        C4
2023-01-01 -0.436596  0.407192  0.088817  0.347263
2023-01-02  0.633264  1.186989  0.934845  1.244085
2023-01-03  0.905392  0.176422  0.945018 -0.821895
2023-01-04  0.119293  0.083757 -1.178566  0.043998


In [111]:
print(df.loc["2023-01-01":"2023-01-04", ["C2", "C4"]])
print(df.at["2023-01-01", "C2"])

                  C2        C4
2023-01-01  0.407192  0.347263
2023-01-02  1.186989  1.244085
2023-01-03  0.176422 -0.821895
2023-01-04  0.083757  0.043998
0.40719231068077416


In [114]:
print(df.iloc[0:4, [1, 3]])
print(df.iat[0, 1])

                  C2        C4
2023-01-01  0.407192  0.347263
2023-01-02  1.186989  1.244085
2023-01-03  0.176422 -0.821895
2023-01-04  0.083757  0.043998
0.40719231068077416


In [115]:
print(df)

                  C1        C2        C3        C4
2023-01-01 -0.436596  0.407192  0.088817  0.347263
2023-01-02  0.633264  1.186989  0.934845  1.244085
2023-01-03  0.905392  0.176422  0.945018 -0.821895
2023-01-04  0.119293  0.083757 -1.178566  0.043998
2023-01-05 -1.926825  0.552893  1.103002  2.670238
2023-01-06  0.108019  1.055340 -0.786042 -1.564110


In [116]:
print(df[df.C3 < 0])

                  C1        C2        C3        C4
2023-01-04  0.119293  0.083757 -1.178566  0.043998
2023-01-06  0.108019  1.055340 -0.786042 -1.564110


In [124]:
df2.loc[3, "E"] = np.nan

In [125]:
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3    NaN  foo


In [126]:
print(df2[df2["E"].isin(["test", "train"])])

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo


In [127]:
df2["G"] = 0

In [128]:
print(df2)

     A          B    C  D      E    F  G
0  1.0 2013-01-02  1.0  3   test  foo  0
1  1.0 2013-01-02  1.0  3  train  foo  0
2  1.0 2013-01-02  1.0  3   test  foo  0
3  1.0 2013-01-02  1.0  3    NaN  foo  0


In [129]:
df2["H"] = [0, 1, 2, 3]
print(df2)

     A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2
3  1.0 2013-01-02  1.0  3    NaN  foo  0  3


In [133]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=["C1", "C2", "C3", "C4"])
print(df)
df[df < 0] = -df
print(df)

                  C1        C2        C3        C4
2023-01-01  0.027908 -0.370542  0.972551  0.472237
2023-01-02 -0.762529 -0.788104 -1.720697  0.270809
2023-01-03 -1.316477 -0.004753  0.490561  0.318505
2023-01-04 -0.132700  1.046339  0.012821 -0.648445
2023-01-05 -0.648799  0.199508  0.228221 -0.591488
2023-01-06  0.192798 -0.626980 -0.886654  1.129173
                  C1        C2        C3        C4
2023-01-01  0.027908  0.370542  0.972551  0.472237
2023-01-02  0.762529  0.788104  1.720697  0.270809
2023-01-03  1.316477  0.004753  0.490561  0.318505
2023-01-04  0.132700  1.046339  0.012821  0.648445
2023-01-05  0.648799  0.199508  0.228221  0.591488
2023-01-06  0.192798  0.626980  0.886654  1.129173


In [134]:
print(df.index)
print(df.columns)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['C1', 'C2', 'C3', 'C4'], dtype='object')


In [135]:
print(df.to_numpy())

[[0.02790782 0.37054233 0.97255109 0.47223731]
 [0.7625287  0.78810427 1.72069714 0.27080873]
 [1.31647669 0.0047532  0.4905614  0.31850526]
 [0.13270007 1.04633895 0.01282055 0.64844524]
 [0.64879887 0.19950792 0.22822067 0.59148776]
 [0.19279777 0.6269798  0.88665375 1.12917293]]


In [137]:
a = df2.to_numpy()
print(a.dtype)

object


In [138]:
df.describe()

C1        C2        C3        C4
count  6.000000  6.000000  6.000000  6.000000
mean   0.513535  0.506038  0.718584  0.571776
std    0.491681  0.387226  0.614415  0.310353
min    0.027908  0.004753  0.012821  0.270809
25%    0.147724  0.242267  0.293806  0.356938
50%    0.420798  0.498761  0.688608  0.531863
75%    0.734096  0.747823  0.951077  0.634206
max    1.316477  1.046339  1.720697  1.129173

In [147]:
print(df)
print(df.T)

                  C1        C2        C3        C4
2023-01-01  0.027908  0.370542  0.972551  0.472237
2023-01-02  0.762529  0.788104  1.720697  0.270809
2023-01-03  1.316477  0.004753  0.490561  0.318505
2023-01-04  0.132700  1.046339  0.012821  0.648445
2023-01-05  0.648799  0.199508  0.228221  0.591488
2023-01-06  0.192798  0.626980  0.886654  1.129173
    2023-01-01  2023-01-02  2023-01-03  2023-01-04  2023-01-05  2023-01-06
C1    0.027908    0.762529    1.316477    0.132700    0.648799    0.192798
C2    0.370542    0.788104    0.004753    1.046339    0.199508    0.626980
C3    0.972551    1.720697    0.490561    0.012821    0.228221    0.886654
C4    0.472237    0.270809    0.318505    0.648445    0.591488    1.129173


In [140]:
print(df)

                  C1        C2        C3        C4
2023-01-01  0.027908  0.370542  0.972551  0.472237
2023-01-02  0.762529  0.788104  1.720697  0.270809
2023-01-03  1.316477  0.004753  0.490561  0.318505
2023-01-04  0.132700  1.046339  0.012821  0.648445
2023-01-05  0.648799  0.199508  0.228221  0.591488
2023-01-06  0.192798  0.626980  0.886654  1.129173


In [141]:
print(df.sort_values(by="C2"))

                  C1        C2        C3        C4
2023-01-03  1.316477  0.004753  0.490561  0.318505
2023-01-05  0.648799  0.199508  0.228221  0.591488
2023-01-01  0.027908  0.370542  0.972551  0.472237
2023-01-06  0.192798  0.626980  0.886654  1.129173
2023-01-02  0.762529  0.788104  1.720697  0.270809
2023-01-04  0.132700  1.046339  0.012821  0.648445


In [142]:
print(df2)

     A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2
3  1.0 2013-01-02  1.0  3    NaN  foo  0  3


In [143]:
print(pd.isna(df2))

       A      B      C      D      E      F      G      H
0  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False
3  False  False  False  False   True  False  False  False


In [144]:
df2.dropna()

A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2

In [145]:
print(df2)

     A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2
3  1.0 2013-01-02  1.0  3    NaN  foo  0  3


In [146]:
df2.fillna(value="train")

A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2
3  1.0 2013-01-02  1.0  3  train  foo  0  3